### ISSUE TITLE
Add a smarter version of Pincer

### ISSUE THREAD

**Issue by krankur** [amethyst/space-menace#14]
### The problem

Pincer but a little smarter, i.e. when hit by a bullet it should start moving in the direction of the player. It should be of different color than its basic version (Reddish may be).

### Expectation

The implementation should be almost identical to that of basic Pincer. Some of the files related to basic Pincer to get started:

https://github.com/amethyst/space-menace/blob/master/src/components/pincer.rs
https://github.com/amethyst/space-menace/blob/master/src/entities/pincer.rs

**Comment by ABoschman** [comment]
I'd like to give this one a go.

**Comment by krankur** [comment]
Awesome! Assigned it to you. Let me know if you need any help.

**Comment by krankur** [comment]
This has been resolved by https://github.com/amethyst/space-menace/pull/38 . Thanks @ABoschman .
