### ISSUE TITLE
Scale issue on HiDPI Monitor (Manjaro Lysia 20.0.1)

### ISSUE THREAD

**Issue by rlueder** [amethyst/space-menace#59]
Hello,

As a side project I'd like to learn Rust and thought a 2D game would be a fun first project.

When running Space Menace on Manjaro 20.0.1 I'm having issues with the size of the window (resizing doesn't help).

I updated `Cargo.toml` features default value to `vulkan` as described in the README

```
[features]
default = ["vulkan"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
```

![space_menace_linux](https://user-images.githubusercontent.com/341543/83799799-faf08680-a66b-11ea-942f-2ecb45a94f8d.gif)

It seems that somehow everything is scaled up, I noticed `load_flier: scale = 2` in the terminal output though that seems unrelated (I set it to 1.0 with no change in the output).

I also noticed `Guessed window DPI factor: 1` in the terminal output, though that seems to be standard from other issues I found on the Amethyst repo.

Any ideas of how I can get it to display correctly?

Terminal output below:
```
cargo run --release
   Compiling xcb v0.8.2
   Compiling x11-clipboard v0.3.3
   Compiling clipboard v0.5.0
   Compiling amethyst_ui v0.10.0
   Compiling amethyst_animation v0.10.0
   Compiling amethyst v0.15.0
   Compiling space-menace v0.1.0 (/home/rafael/Github/space-menace)
warning: unused import: `GenericBox`
  --> src/entities/flier.rs:15:28
   |
15 |         Directions, Flier, GenericBox, Motion,
   |                            ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 36.83s
     Running `target/release/space-menace`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.45.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 9912925c254589f58338cb2993163e618475ff75
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
Xlib:  extension "NV-GLX" missing on display ":1".
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
load_flier: scale = 2
```
Thanks!

**Comment by rlueder** [comment]
Doing some research on the issue, it seems related to my hidpi monitor (LG 34UC80-B QHD) and not the OS itself.

This forum topic seems to describe a related issue with scaling sprites: https://community.amethyst.rs/t/adjusting-window-sprites-according-to-windows-ui-scale-settings-dpi/1240

Still digging, found some other HiDPI issues on Amethyst, adding for my own reference:
https://github.com/amethyst/amethyst/issues/1265
https://github.com/amethyst/amethyst/issues/1264
https://github.com/amethyst/amethyst/issues/1241
https://github.com/amethyst/amethyst/pull/1219
https://github.com/amethyst/amethyst/issues/943
https://wiki.archlinux.org/index.php/HiDPI

**Comment by Jazarro** [comment]
I was having this issue as well, it turns out that in commit f65cbde1d025528b700a16493ee36993f89b6307 the size of the window was reduced to 600 by 352. 

As a temporary solution, you could change the `dimensions` values in the `resources/display_config.ron` to something more agreeable to you. This would allow you to run and play the game properly.

**Comment by ghost** [comment]
I think 800x600 should be fine in most cases.
